/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fmy_framestudyapplication_HellowJni */

#ifndef _Included_com_example_fmy_framestudyapplication_HellowJni
#define _Included_com_example_fmy_framestudyapplication_HellowJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fmy_framestudyapplication_HellowJni
 * Method:    getStrFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fmy_framestudyapplication_HellowJni_getStrFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_example_fmy_framestudyapplication_HellowJni
 * Method:    getAdd
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fmy_framestudyapplication_HellowJni_getAdd
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
